[tool.poetry]
name = "quart-babel"
version = "0.0.1"
description = "Translations for Quart."
authors = ["Chris Rood <quart.addons@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Babel = "^2.10.3"
ipapi = "^1.0.4"
quart = "^0.18.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-asyncio = "^0.19.0"
Sphinx = "^5.1.1"
pydata-sphinx-theme = "^0.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
