[tool.poetry]
name = "quart-babel-dev2"
version = "1.0.0"
description = ""
authors = ["crood58 <crood58@gmail.com>"]
readme = "README.md"
packages = [{include = "quart_babel_dev2"}]

[tool.poetry.dependencies]
python = "^3.10"
quart = "^0.18.3"
Babel = "^2.11.0"
asgi-tools = "^0.64.2"
aioipapi = "^0.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pytest-asyncio = "^0.20.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
